<?php

use Illuminate\Database\Seeder;

class BrandsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('brands')->delete();

        \DB::table('brands')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'Uniqlo',
                'name_l' => 'Uniqlo',
                'slug' => 'uniqlo',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:32',
                'updated_at' => '2019-06-06 09:02:32',
                'deleted_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'H&M',
                'name_l' => 'H&M',
                'slug' => 'hm',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:32',
                'updated_at' => '2019-06-06 09:02:32',
                'deleted_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'Zara',
                'name_l' => 'Zara',
                'slug' => 'zara',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:33',
                'updated_at' => '2019-06-06 09:02:33',
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'Nike',
                'name_l' => 'Nike',
                'slug' => 'nike',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:33',
                'updated_at' => '2019-06-06 09:02:33',
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'name' => 'Adidas',
                'name_l' => 'Adidas',
                'slug' => 'adidas',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:33',
                'updated_at' => '2019-06-06 09:02:33',
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'name' => 'Ripcurl',
                'name_l' => 'Ripcurl',
                'slug' => 'ripcurl',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:33',
                'updated_at' => '2019-06-06 09:02:33',
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'name' => 'Cotton On',
                'name_l' => 'Cotton On',
                'slug' => 'cotton-on',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:33',
                'updated_at' => '2019-06-06 09:02:33',
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'name' => 'Pull and bear',
                'name_l' => 'Pull and bear',
                'slug' => 'pull-and-bear',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:33',
                'updated_at' => '2019-06-06 09:02:33',
                'deleted_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'name' => 'Giordano',
                'name_l' => 'Giordano',
                'slug' => 'giordano',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:33',
                'updated_at' => '2019-06-06 09:02:33',
                'deleted_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'name' => 'Muji',
                'name_l' => 'Muji',
                'slug' => 'muji',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:33',
                'updated_at' => '2019-06-06 09:02:33',
                'deleted_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'name' => 'Topman',
                'name_l' => 'Topman',
                'slug' => 'topman',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:33',
                'updated_at' => '2019-06-06 09:02:33',
                'deleted_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'name' => 'Levis',
                'name_l' => 'Levis',
                'slug' => 'levis',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:33',
                'updated_at' => '2019-06-06 09:02:33',
                'deleted_at' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'name' => 'Guess',
                'name_l' => 'Guess',
                'slug' => 'guess',
                'description' => 'default',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:33',
                'updated_at' => '2019-06-06 09:02:33',
                'deleted_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'name' => 'Banana Republic',
                'name_l' => 'Banana Republic',
                'slug' => 'banana-republic',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:33',
                'updated_at' => '2019-06-06 09:02:33',
                'deleted_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'name' => 'Gap',
                'name_l' => 'Gap',
                'slug' => 'gap',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:33',
                'updated_at' => '2019-06-06 09:02:33',
                'deleted_at' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'name' => 'Abercrombie & Fitch',
                'name_l' => 'Abercrombie & Fitch',
                'slug' => 'abercrombie-fitch',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:34',
                'updated_at' => '2019-06-06 09:02:34',
                'deleted_at' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'name' => 'Hollister',
                'name_l' => 'Hollister',
                'slug' => 'hollister',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:34',
                'updated_at' => '2019-06-06 09:02:34',
                'deleted_at' => NULL,
            ),
            17 =>
            array (
                'id' => 18,
                'name' => 'Vans',
                'name_l' => 'Vans',
                'slug' => 'vans',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:34',
                'updated_at' => '2019-06-06 09:02:34',
                'deleted_at' => NULL,
            ),
            18 =>
            array (
                'id' => 19,
                'name' => 'Reebok',
                'name_l' => 'Reebok',
                'slug' => 'reebok',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:34',
                'updated_at' => '2019-06-06 09:02:34',
                'deleted_at' => NULL,
            ),
            19 =>
            array (
                'id' => 20,
                'name' => 'Converse',
                'name_l' => 'Converse',
                'slug' => 'converse',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:34',
                'updated_at' => '2019-06-06 09:02:34',
                'deleted_at' => NULL,
            ),
            20 =>
            array (
                'id' => 21,
                'name' => 'Everbest',
                'name_l' => 'Everbest',
                'slug' => 'everbest',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:34',
                'updated_at' => '2019-06-06 09:02:34',
                'deleted_at' => NULL,
            ),
            21 =>
            array (
                'id' => 22,
                'name' => 'Pedro',
                'name_l' => 'Pedro',
                'slug' => 'pedro',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:34',
                'updated_at' => '2019-06-06 09:02:34',
                'deleted_at' => NULL,
            ),
            22 =>
            array (
                'id' => 23,
                'name' => 'Aldo',
                'name_l' => 'Aldo',
                'slug' => 'aldo',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:34',
                'updated_at' => '2019-06-06 09:02:34',
                'deleted_at' => NULL,
            ),
            23 =>
            array (
                'id' => 24,
                'name' => 'Topshop',
                'name_l' => 'Topshop',
                'slug' => 'topshop',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:34',
                'updated_at' => '2019-06-06 09:02:34',
                'deleted_at' => NULL,
            ),
            24 =>
            array (
                'id' => 25,
                'name' => 'Bershka',
                'name_l' => 'Bershka',
                'slug' => 'bershka',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:34',
                'updated_at' => '2019-06-06 09:02:34',
                'deleted_at' => NULL,
            ),
            25 =>
            array (
                'id' => 26,
                'name' => 'Forever 21',
                'name_l' => 'Forever 21',
                'slug' => 'forever-21',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:34',
                'updated_at' => '2019-06-06 09:02:34',
                'deleted_at' => NULL,
            ),
            26 =>
            array (
                'id' => 27,
                'name' => 'Heim',
                'name_l' => 'Heim',
                'slug' => 'heim',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:34',
                'updated_at' => '2019-06-06 09:02:34',
                'deleted_at' => NULL,
            ),
            27 =>
            array (
                'id' => 28,
                'name' => 'Nappa Milano',
                'name_l' => 'Nappa Milano',
                'slug' => 'nappa-milano',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:34',
                'updated_at' => '2019-06-06 09:02:34',
                'deleted_at' => NULL,
            ),
            28 =>
            array (
                'id' => 29,
                'name' => 'Orange Poppin',
                'name_l' => 'Orange Poppin',
                'slug' => 'orange-poppin',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:34',
                'updated_at' => '2019-06-06 09:02:34',
                'deleted_at' => NULL,
            ),
            29 =>
            array (
                'id' => 30,
                'name' => 'Hale+',
                'name_l' => 'Hale+',
                'slug' => 'hale',
                'description' => '0',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:35',
                'updated_at' => '2019-06-06 09:02:35',
                'deleted_at' => NULL,
            ),
            30 =>
            array (
                'id' => 31,
                'name' => 'Timechine Co.',
                'name_l' => 'Timechine Co.',
                'slug' => 'timechine-co',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:35',
                'updated_at' => '2019-06-06 09:02:35',
                'deleted_at' => NULL,
            ),
            31 =>
            array (
                'id' => 32,
                'name' => 'Sorta Studio',
                'name_l' => 'Sorta Studio',
                'slug' => 'sorta-studio',
                'description' => '0',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:35',
                'updated_at' => '2019-06-06 09:02:35',
                'deleted_at' => NULL,
            ),
            32 =>
            array (
                'id' => 33,
                'name' => 'Tujuh',
                'name_l' => 'Tujuh',
                'slug' => 'tujuh',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:35',
                'updated_at' => '2019-06-06 09:02:35',
                'deleted_at' => NULL,
            ),
            33 =>
            array (
                'id' => 34,
                'name' => 'Nike SB',
                'name_l' => 'Nike SB',
                'slug' => 'nike-sb',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:35',
                'updated_at' => '2019-06-06 09:02:35',
                'deleted_at' => NULL,
            ),
            34 =>
            array (
                'id' => 35,
                'name' => 'Tods',
                'name_l' => 'Tods',
                'slug' => 'tods',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:35',
                'updated_at' => '2019-06-06 09:02:35',
                'deleted_at' => NULL,
            ),
            35 =>
            array (
                'id' => 36,
                'name' => 'Superga',
                'name_l' => 'Superga',
                'slug' => 'superga',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:35',
                'updated_at' => '2019-06-06 09:02:35',
                'deleted_at' => NULL,
            ),
            36 =>
            array (
                'id' => 37,
                'name' => 'Puma',
                'name_l' => 'Puma',
                'slug' => 'puma',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:35',
                'updated_at' => '2019-06-06 09:02:35',
                'deleted_at' => NULL,
            ),
            37 =>
            array (
                'id' => 38,
                'name' => 'Fred Perry',
                'name_l' => 'Fred Perry',
                'slug' => 'fred-perry',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:35',
                'updated_at' => '2019-06-06 09:02:35',
                'deleted_at' => NULL,
            ),
            38 =>
            array (
                'id' => 39,
                'name' => 'Uniqlo Shorts',
                'name_l' => 'Uniqlo Shorts',
                'slug' => 'uniqlo-shorts',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:35',
                'updated_at' => '2019-06-06 09:02:35',
                'deleted_at' => NULL,
            ),
            39 =>
            array (
                'id' => 40,
                'name' => 'Uniqlo Chinos',
                'name_l' => 'Uniqlo Chinos',
                'slug' => 'uniqlo-chinos',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:35',
                'updated_at' => '2019-06-06 09:02:35',
                'deleted_at' => NULL,
            ),
            40 =>
            array (
                'id' => 41,
                'name' => 'Lacoste - Polo Original Fit',
                'name_l' => 'Lacoste - Polo Original Fit',
                'slug' => 'lacoste-polo-original-fit',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:35',
                'updated_at' => '2019-06-06 09:02:35',
                'deleted_at' => NULL,
            ),
            41 =>
            array (
                'id' => 42,
                'name' => 'Uniqlo Jeans',
                'name_l' => 'Uniqlo Jeans',
                'slug' => 'uniqlo-jeans',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:35',
                'updated_at' => '2019-06-06 09:02:35',
                'deleted_at' => NULL,
            ),
            42 =>
            array (
                'id' => 43,
                'name' => 'Lacoste - Polo Regular Fit',
                'name_l' => 'Lacoste - Polo Regular Fit',
                'slug' => 'lacoste-polo-regular-fit',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:35',
                'updated_at' => '2019-06-06 09:02:35',
                'deleted_at' => NULL,
            ),
            43 =>
            array (
                'id' => 44,
                'name' => 'Lacoste - Polo Slim Fit',
                'name_l' => 'Lacoste - Polo Slim Fit',
                'slug' => 'lacoste-polo-slim-fit',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:35',
                'updated_at' => '2019-06-06 09:02:35',
                'deleted_at' => NULL,
            ),
            44 =>
            array (
                'id' => 45,
                'name' => 'Zara Shorts',
                'name_l' => 'Zara Shorts',
                'slug' => 'zara-shorts',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:36',
                'updated_at' => '2019-06-06 09:02:36',
                'deleted_at' => NULL,
            ),
            45 =>
            array (
                'id' => 46,
                'name' => 'Zara Trousers & Jeans',
                'name_l' => 'Zara Trousers & Jeans',
                'slug' => 'zara-trousers-jeans',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:36',
                'updated_at' => '2019-06-06 09:02:36',
                'deleted_at' => NULL,
            ),
            46 =>
            array (
                'id' => 47,
                'name' => 'Maison Kitsune - Oxford Shirt',
                'name_l' => 'Maison Kitsune - Oxford Shirt',
                'slug' => 'maison-kitsune-oxford-shirt',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:36',
                'updated_at' => '2019-06-06 09:02:36',
                'deleted_at' => NULL,
            ),
            47 =>
            array (
                'id' => 48,
                'name' => 'Maison Kitsune - T-Shirt',
                'name_l' => 'Maison Kitsune - T-Shirt',
                'slug' => 'maison-kitsune-t-shirt',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:36',
                'updated_at' => '2019-06-06 09:02:36',
                'deleted_at' => NULL,
            ),
            48 =>
            array (
                'id' => 49,
                'name' => 'Muji Denim',
                'name_l' => 'Muji Denim',
                'slug' => 'muji-denim',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:36',
                'updated_at' => '2019-06-06 09:02:36',
                'deleted_at' => NULL,
            ),
            49 =>
            array (
                'id' => 50,
                'name' => 'Muji Bottom',
                'name_l' => 'Muji Bottom',
                'slug' => 'muji-bottom',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:36',
                'updated_at' => '2019-06-06 09:02:36',
                'deleted_at' => NULL,
            ),
            50 =>
            array (
                'id' => 51,
                'name' => 'Uniqlo Shorts / Skirts',
                'name_l' => 'Uniqlo Shorts / Skirts',
                'slug' => 'uniqlo-shorts-skirts',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:36',
                'updated_at' => '2019-06-06 09:02:36',
                'deleted_at' => NULL,
            ),
            51 =>
            array (
                'id' => 52,
                'name' => 'H&M Jeans',
                'name_l' => 'H&M Jeans',
                'slug' => 'hm-jeans',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:36',
                'updated_at' => '2019-06-06 09:02:36',
                'deleted_at' => NULL,
            ),
            52 =>
            array (
                'id' => 53,
                'name' => 'Uniqlo Pants',
                'name_l' => 'Uniqlo Pants',
                'slug' => 'uniqlo-pants',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:36',
                'updated_at' => '2019-06-06 09:02:36',
                'deleted_at' => NULL,
            ),
            53 =>
            array (
                'id' => 54,
                'name' => 'H&M Trousers',
                'name_l' => 'H&M Trousers',
                'slug' => 'hm-trousers',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:36',
                'updated_at' => '2019-06-06 09:02:36',
                'deleted_at' => NULL,
            ),
            54 =>
            array (
                'id' => 55,
                'name' => 'Uniqlo Jeans',
                'name_l' => 'Uniqlo Jeans',
                'slug' => 'uniqlo-jeans',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:36',
                'updated_at' => '2019-06-06 09:02:36',
                'deleted_at' => NULL,
            ),
            55 =>
            array (
                'id' => 56,
                'name' => 'Lee Cooper Slim Fit',
                'name_l' => 'Lee Cooper Slim Fit',
                'slug' => 'lee-cooper-slim-fit',
                'description' => 'default',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:36',
                'updated_at' => '2019-06-06 09:02:36',
                'deleted_at' => NULL,
            ),
            56 =>
            array (
                'id' => 57,
                'name' => 'Lee cooper',
                'name_l' => 'Lee cooper',
                'slug' => 'lee-cooper',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:36',
                'updated_at' => '2019-06-06 09:02:36',
                'deleted_at' => NULL,
            ),
            57 =>
            array (
                'id' => 58,
                'name' => 'Hollister Pants/Skirts',
                'name_l' => 'Hollister Pants/Skirts',
                'slug' => 'hollister-pantsskirts',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:36',
                'updated_at' => '2019-06-06 09:02:36',
                'deleted_at' => NULL,
            ),
            58 =>
            array (
                'id' => 59,
                'name' => 'Hollister Jeans',
                'name_l' => 'Hollister Jeans',
                'slug' => 'hollister-jeans',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:37',
                'updated_at' => '2019-06-06 09:02:37',
                'deleted_at' => NULL,
            ),
            59 =>
            array (
                'id' => 60,
                'name' => 'Billabong',
                'name_l' => 'Billabong',
                'slug' => 'billabong',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:37',
                'updated_at' => '2019-06-06 09:02:37',
                'deleted_at' => NULL,
            ),
            60 =>
            array (
                'id' => 61,
                'name' => 'H&M Skirts',
                'name_l' => 'H&M Skirts',
                'slug' => 'hm-skirts',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:37',
                'updated_at' => '2019-06-06 09:02:37',
                'deleted_at' => NULL,
            ),
            61 =>
            array (
                'id' => 62,
                'name' => 'Bershka Jeans',
                'name_l' => 'Bershka Jeans',
                'slug' => 'bershka-jeans',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:37',
                'updated_at' => '2019-06-06 09:02:37',
                'deleted_at' => NULL,
            ),
            62 =>
            array (
                'id' => 63,
                'name' => 'H&M Trousers / Shorts',
                'name_l' => 'H&M Trousers / Shorts',
                'slug' => 'hm-trousers-shorts',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:37',
                'updated_at' => '2019-06-06 09:02:37',
                'deleted_at' => NULL,
            ),
            63 =>
            array (
                'id' => 64,
                'name' => 'Bershka Pants',
                'name_l' => 'Bershka Pants',
                'slug' => 'bershka-pants',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:37',
                'updated_at' => '2019-06-06 09:02:37',
                'deleted_at' => NULL,
            ),
            64 =>
            array (
                'id' => 65,
                'name' => 'Zara Jeans',
                'name_l' => 'Zara Jeans',
                'slug' => 'zara-jeans',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:37',
                'updated_at' => '2019-06-06 09:02:37',
                'deleted_at' => NULL,
            ),
            65 =>
            array (
                'id' => 66,
                'name' => 'Forever 21 Jeans',
                'name_l' => 'Forever 21 Jeans',
                'slug' => 'forever-21-jeans',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:37',
                'updated_at' => '2019-06-06 09:02:37',
                'deleted_at' => NULL,
            ),
            66 =>
            array (
                'id' => 67,
                'name' => 'Zara Trousers',
                'name_l' => 'Zara Trousers',
                'slug' => 'zara-trousers',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:37',
                'updated_at' => '2019-06-06 09:02:37',
                'deleted_at' => NULL,
            ),
            67 =>
            array (
                'id' => 68,
                'name' => 'Forever 21 Pants',
                'name_l' => 'Forever 21 Pants',
                'slug' => 'forever-21-pants',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:37',
                'updated_at' => '2019-06-06 09:02:37',
                'deleted_at' => NULL,
            ),
            68 =>
            array (
                'id' => 69,
                'name' => 'Vezzo',
                'name_l' => 'Vezzo',
                'slug' => 'vezzo',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:37',
                'updated_at' => '2019-06-06 09:02:37',
                'deleted_at' => NULL,
            ),
            69 =>
            array (
                'id' => 70,
                'name' => 'Aloha Attire',
                'name_l' => 'Aloha Attire',
                'slug' => 'aloha-attire',
                'description' => '0',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:37',
                'updated_at' => '2019-06-06 09:02:37',
                'deleted_at' => NULL,
            ),
            70 =>
            array (
                'id' => 71,
                'name' => 'Filbert',
                'name_l' => 'Filbert',
                'slug' => 'filbert',
                'description' => '0',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:37',
                'updated_at' => '2019-06-06 09:02:37',
                'deleted_at' => NULL,
            ),
            71 =>
            array (
                'id' => 72,
                'name' => 'PRJCT',
                'name_l' => 'PRJCT',
                'slug' => 'prjct',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:37',
                'updated_at' => '2019-06-06 09:02:37',
                'deleted_at' => NULL,
            ),
            72 =>
            array (
                'id' => 73,
                'name' => 'Street No. 55',
                'name_l' => 'Street No. 55',
                'slug' => 'street-no-55',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:38',
                'updated_at' => '2019-06-06 09:02:38',
                'deleted_at' => NULL,
            ),
            73 =>
            array (
                'id' => 74,
                'name' => 'filbert',
                'name_l' => 'filbert',
                'slug' => 'filbert',
                'description' => '0',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:38',
                'updated_at' => '2019-06-06 09:02:38',
                'deleted_at' => NULL,
            ),
            74 =>
            array (
                'id' => 75,
                'name' => 'TEST',
                'name_l' => 'TEST',
                'slug' => 'test',
                'description' => '0',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:38',
                'updated_at' => '2019-06-06 09:02:38',
                'deleted_at' => NULL,
            ),
            75 =>
            array (
                'id' => 76,
                'name' => 'KOMMA',
                'name_l' => 'KOMMA',
                'slug' => 'komma',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:38',
                'updated_at' => '2019-06-06 09:02:38',
                'deleted_at' => NULL,
            ),
            76 =>
            array (
                'id' => 77,
                'name' => 'DARA',
                'name_l' => 'DARA',
                'slug' => 'dara',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:38',
                'updated_at' => '2019-06-06 09:02:38',
                'deleted_at' => NULL,
            ),
            77 =>
            array (
                'id' => 78,
                'name' => 'Fancy Weeknd',
                'name_l' => 'Fancy Weeknd',
                'slug' => 'fancy-weeknd',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:38',
                'updated_at' => '2019-06-06 09:02:38',
                'deleted_at' => NULL,
            ),
            78 =>
            array (
                'id' => 79,
                'name' => 'Mon Akita',
                'name_l' => 'Mon Akita',
                'slug' => 'mon-akita',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:38',
                'updated_at' => '2019-06-06 09:02:38',
                'deleted_at' => NULL,
            ),
            79 =>
            array (
                'id' => 80,
                'name' => 'Cosmonauts',
                'name_l' => 'Cosmonauts',
                'slug' => 'cosmonauts',
                'description' => '0',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:38',
                'updated_at' => '2019-06-06 09:02:38',
                'deleted_at' => NULL,
            ),
            80 =>
            array (
                'id' => 81,
                'name' => 'Lecathva',
                'name_l' => 'Lecathva',
                'slug' => 'lecathva',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:38',
                'updated_at' => '2019-06-06 09:02:38',
                'deleted_at' => NULL,
            ),
            81 =>
            array (
                'id' => 82,
                'name' => 'Tees and Scissors',
                'name_l' => 'Tees and Scissors',
                'slug' => 'tees-and-scissors',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:38',
                'updated_at' => '2019-06-06 09:02:38',
                'deleted_at' => NULL,
            ),
            82 =>
            array (
                'id' => 83,
                'name' => 'RENOIR',
                'name_l' => 'RENOIR',
                'slug' => 'renoir',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:38',
                'updated_at' => '2019-06-06 09:02:38',
                'deleted_at' => NULL,
            ),
            83 =>
            array (
                'id' => 84,
                'name' => 'JACKHAMMER CO.',
                'name_l' => 'JACKHAMMER CO.',
                'slug' => 'jackhammer-co',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:38',
                'updated_at' => '2019-06-06 09:02:38',
                'deleted_at' => NULL,
            ),
            84 =>
            array (
                'id' => 85,
                'name' => 'Yes Means Please',
                'name_l' => 'Yes Means Please',
                'slug' => 'yes-means-please',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:38',
                'updated_at' => '2019-06-06 09:02:38',
                'deleted_at' => NULL,
            ),
            85 =>
            array (
                'id' => 86,
                'name' => 'FLVX',
                'name_l' => 'FLVX',
                'slug' => 'flvx',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:38',
                'updated_at' => '2019-06-06 09:02:38',
                'deleted_at' => NULL,
            ),
            86 =>
            array (
                'id' => 87,
                'name' => 'Jean Jackson',
                'name_l' => 'Jean Jackson',
                'slug' => 'jean-jackson',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:38',
                'updated_at' => '2019-06-06 09:02:38',
                'deleted_at' => NULL,
            ),
            87 =>
            array (
                'id' => 88,
                'name' => 'filbert',
                'name_l' => 'filbert',
                'slug' => 'filbert',
                'description' => '0',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:38',
                'updated_at' => '2019-06-06 09:02:38',
                'deleted_at' => NULL,
            ),
            88 =>
            array (
                'id' => 89,
                'name' => 'ORE',
                'name_l' => 'ORE',
                'slug' => 'ore',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:38',
                'updated_at' => '2019-06-06 09:02:38',
                'deleted_at' => NULL,
            ),
            89 =>
            array (
                'id' => 90,
                'name' => 'New Balance',
                'name_l' => 'New Balance',
                'slug' => 'new-balance',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:39',
                'updated_at' => '2019-06-06 09:02:39',
                'deleted_at' => NULL,
            ),
            90 =>
            array (
                'id' => 91,
                'name' => 'Hurley',
                'name_l' => 'Hurley',
                'slug' => 'hurley',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:39',
                'updated_at' => '2019-06-06 09:02:39',
                'deleted_at' => NULL,
            ),
            91 =>
            array (
                'id' => 92,
                'name' => 'Statements by Proud',
                'name_l' => 'Statements by Proud',
                'slug' => 'statements-by-proud',
                'description' => '0',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:39',
                'updated_at' => '2019-06-06 09:02:39',
                'deleted_at' => NULL,
            ),
            92 =>
            array (
                'id' => 93,
                'name' => 'Lanccelot',
                'name_l' => 'Lanccelot',
                'slug' => 'lanccelot',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:39',
                'updated_at' => '2019-06-06 09:02:39',
                'deleted_at' => NULL,
            ),
            93 =>
            array (
                'id' => 94,
                'name' => 'Sinau',
                'name_l' => 'Sinau',
                'slug' => 'sinau',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:39',
                'updated_at' => '2019-06-06 09:02:39',
                'deleted_at' => NULL,
            ),
            94 =>
            array (
                'id' => 95,
                'name' => 'Obie',
                'name_l' => 'Obie',
                'slug' => 'obie',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:39',
                'updated_at' => '2019-06-06 09:02:39',
                'deleted_at' => NULL,
            ),
            95 =>
            array (
                'id' => 96,
                'name' => 'Ilavera',
                'name_l' => 'Ilavera',
                'slug' => 'ilavera',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:39',
                'updated_at' => '2019-06-06 09:02:39',
                'deleted_at' => NULL,
            ),
            96 =>
            array (
                'id' => 97,
                'name' => 'Hooman Bags',
                'name_l' => 'Hooman Bags',
                'slug' => 'hooman-bags',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:39',
                'updated_at' => '2019-06-06 09:02:39',
                'deleted_at' => NULL,
            ),
            97 =>
            array (
                'id' => 98,
                'name' => 'Groot Watch',
                'name_l' => 'Groot Watch',
                'slug' => 'groot-watch',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:39',
                'updated_at' => '2019-06-06 09:02:39',
                'deleted_at' => NULL,
            ),
            98 =>
            array (
                'id' => 99,
                'name' => 'Guilty Pleasure',
                'name_l' => 'Guilty Pleasure',
                'slug' => 'guilty-pleasure',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:39',
                'updated_at' => '2019-06-06 09:02:39',
                'deleted_at' => NULL,
            ),
            99 =>
            array (
                'id' => 100,
                'name' => 'Gentlehomme',
                'name_l' => 'Gentlehomme',
                'slug' => 'gentlehomme',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:39',
                'updated_at' => '2019-06-06 09:02:39',
                'deleted_at' => NULL,
            ),
            100 =>
            array (
                'id' => 101,
                'name' => '2Fab4you',
                'name_l' => '2Fab4you',
                'slug' => '2fab4you',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:39',
                'updated_at' => '2019-06-06 09:02:39',
                'deleted_at' => NULL,
            ),
            101 =>
            array (
                'id' => 102,
                'name' => 'Major Liner',
                'name_l' => 'Major Liner',
                'slug' => 'major-liner',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:39',
                'updated_at' => '2019-06-06 09:02:39',
                'deleted_at' => NULL,
            ),
            102 =>
            array (
                'id' => 103,
                'name' => 'The Pixie Rack',
                'name_l' => 'The Pixie Rack',
                'slug' => 'the-pixie-rack',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:39',
                'updated_at' => '2019-06-06 09:02:39',
                'deleted_at' => NULL,
            ),
            103 =>
            array (
                'id' => 104,
                'name' => 'Blanc 22',
                'name_l' => 'Blanc 22',
                'slug' => 'blanc-22',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:40',
                'updated_at' => '2019-06-06 09:02:40',
                'deleted_at' => NULL,
            ),
            104 =>
            array (
                'id' => 105,
                'name' => 'Adora',
                'name_l' => 'Adora',
                'slug' => 'adora',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:40',
                'updated_at' => '2019-06-06 09:02:40',
                'deleted_at' => NULL,
            ),
            105 =>
            array (
                'id' => 106,
                'name' => 'Giwang',
                'name_l' => 'Giwang',
                'slug' => 'giwang',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:40',
                'updated_at' => '2019-06-06 09:02:40',
                'deleted_at' => NULL,
            ),
            106 =>
            array (
                'id' => 107,
                'name' => 'Soubi Girl',
                'name_l' => 'Soubi Girl',
                'slug' => 'soubi-girl',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:40',
                'updated_at' => '2019-06-06 09:02:40',
                'deleted_at' => NULL,
            ),
            107 =>
            array (
                'id' => 108,
                'name' => 'Ratel',
                'name_l' => 'Ratel',
                'slug' => 'ratel',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:40',
                'updated_at' => '2019-06-06 09:02:40',
                'deleted_at' => NULL,
            ),
            108 =>
            array (
                'id' => 109,
                'name' => 'Tee bags',
                'name_l' => 'Tee bags',
                'slug' => 'tee-bags',
                'description' => '0',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:40',
                'updated_at' => '2019-06-06 09:02:40',
                'deleted_at' => NULL,
            ),
            109 =>
            array (
                'id' => 110,
                'name' => 'Bianero',
                'name_l' => 'Bianero',
                'slug' => 'bianero',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:40',
                'updated_at' => '2019-06-06 09:02:40',
                'deleted_at' => NULL,
            ),
            110 =>
            array (
                'id' => 111,
                'name' => 'Monday Blues',
                'name_l' => 'Monday Blues',
                'slug' => 'monday-blues',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:40',
                'updated_at' => '2019-06-06 09:02:40',
                'deleted_at' => NULL,
            ),
            111 =>
            array (
                'id' => 112,
                'name' => 'Binzu',
                'name_l' => 'Binzu',
                'slug' => 'binzu',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:40',
                'updated_at' => '2019-06-06 09:02:40',
                'deleted_at' => NULL,
            ),
            112 =>
            array (
                'id' => 113,
                'name' => 'Iyagi',
                'name_l' => 'Iyagi',
                'slug' => 'iyagi',
                'description' => '0',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:40',
                'updated_at' => '2019-06-06 09:02:40',
                'deleted_at' => NULL,
            ),
            113 =>
            array (
                'id' => 114,
                'name' => 'Femme Fatale',
                'name_l' => 'Femme Fatale',
                'slug' => 'femme-fatale',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:40',
                'updated_at' => '2019-06-06 09:02:40',
                'deleted_at' => NULL,
            ),
            114 =>
            array (
                'id' => 115,
                'name' => 'Kai and Nyle',
                'name_l' => 'Kai and Nyle',
                'slug' => 'kai-and-nyle',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:40',
                'updated_at' => '2019-06-06 09:02:40',
                'deleted_at' => NULL,
            ),
            115 =>
            array (
                'id' => 116,
                'name' => 'De Sansekerta',
                'name_l' => 'De Sansekerta',
                'slug' => 'de-sansekerta',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:40',
                'updated_at' => '2019-06-06 09:02:40',
                'deleted_at' => NULL,
            ),
            116 =>
            array (
                'id' => 117,
                'name' => 'AIME',
                'name_l' => 'AIME',
                'slug' => 'aime',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:41',
                'updated_at' => '2019-06-06 09:02:41',
                'deleted_at' => NULL,
            ),
            117 =>
            array (
                'id' => 118,
                'name' => 'Le Bijou',
                'name_l' => 'Le Bijou',
                'slug' => 'le-bijou',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:41',
                'updated_at' => '2019-06-06 09:02:41',
                'deleted_at' => NULL,
            ),
            118 =>
            array (
                'id' => 119,
                'name' => 'CDE',
                'name_l' => 'CDE',
                'slug' => 'cde',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:41',
                'updated_at' => '2019-06-06 09:02:41',
                'deleted_at' => NULL,
            ),
            119 =>
            array (
                'id' => 120,
                'name' => 'Tobbo Socks',
                'name_l' => 'Tobbo Socks',
                'slug' => 'tobbo-socks',
                'description' => '0',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:41',
                'updated_at' => '2019-06-06 09:02:41',
                'deleted_at' => NULL,
            ),
            120 =>
            array (
                'id' => 121,
                'name' => 'Kamala Jewelry',
                'name_l' => 'Kamala Jewelry',
                'slug' => 'kamala-jewelry',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:41',
                'updated_at' => '2019-06-06 09:02:41',
                'deleted_at' => NULL,
            ),
            121 =>
            array (
                'id' => 122,
                'name' => 'test',
                'name_l' => 'test',
                'slug' => 'test',
                'description' => '0',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:41',
                'updated_at' => '2019-06-06 09:02:41',
                'deleted_at' => NULL,
            ),
            122 =>
            array (
                'id' => 123,
                'name' => 'Gravity Element',
                'name_l' => 'Gravity Element',
                'slug' => 'gravity-element',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:41',
                'updated_at' => '2019-06-06 09:02:41',
                'deleted_at' => NULL,
            ),
            123 =>
            array (
                'id' => 124,
                'name' => 'Future Tense',
                'name_l' => 'Future Tense',
                'slug' => 'future-tense',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:41',
                'updated_at' => '2019-06-06 09:02:41',
                'deleted_at' => NULL,
            ),
            124 =>
            array (
                'id' => 125,
                'name' => 'Saje Jewelry',
                'name_l' => 'Saje Jewelry',
                'slug' => 'saje-jewelry',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:41',
                'updated_at' => '2019-06-06 09:02:41',
                'deleted_at' => NULL,
            ),
            125 =>
            array (
                'id' => 126,
                'name' => 'Barefoot',
                'name_l' => 'Barefoot',
                'slug' => 'barefoot',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:41',
                'updated_at' => '2019-06-06 09:02:41',
                'deleted_at' => NULL,
            ),
            126 =>
            array (
                'id' => 127,
                'name' => '2madison Avenue',
                'name_l' => '2madison Avenue',
                'slug' => '2madison-avenue',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:41',
                'updated_at' => '2019-06-06 09:02:41',
                'deleted_at' => NULL,
            ),
            127 =>
            array (
                'id' => 128,
                'name' => 'Svata',
                'name_l' => 'Svata',
                'slug' => 'svata',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:41',
                'updated_at' => '2019-06-06 09:02:41',
                'deleted_at' => NULL,
            ),
            128 =>
            array (
                'id' => 129,
                'name' => 'Nolsams',
                'name_l' => 'Nolsams',
                'slug' => 'nolsams',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:42',
                'updated_at' => '2019-06-06 09:02:42',
                'deleted_at' => NULL,
            ),
            129 =>
            array (
                'id' => 130,
                'name' => 'Dotcomma',
                'name_l' => 'Dotcomma',
                'slug' => 'dotcomma',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:42',
                'updated_at' => '2019-06-06 09:02:42',
                'deleted_at' => NULL,
            ),
            130 =>
            array (
                'id' => 131,
                'name' => 'Kinobo',
                'name_l' => 'Kinobo',
                'slug' => 'kinobo',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:42',
                'updated_at' => '2019-06-06 09:02:42',
                'deleted_at' => NULL,
            ),
            131 =>
            array (
                'id' => 132,
                'name' => 'Sleipnir',
                'name_l' => 'Sleipnir',
                'slug' => 'sleipnir',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:42',
                'updated_at' => '2019-06-06 09:02:42',
                'deleted_at' => NULL,
            ),
            132 =>
            array (
                'id' => 133,
                'name' => 'Nuntno',
                'name_l' => 'Nuntno',
                'slug' => 'nuntno',
                'description' => '0',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:42',
                'updated_at' => '2019-06-06 09:02:42',
                'deleted_at' => NULL,
            ),
            133 =>
            array (
                'id' => 134,
                'name' => 'By Obsidia',
                'name_l' => 'By Obsidia',
                'slug' => 'by-obsidia',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:42',
                'updated_at' => '2019-06-06 09:02:42',
                'deleted_at' => NULL,
            ),
            134 =>
            array (
                'id' => 135,
                'name' => 'Cotton Fighter',
                'name_l' => 'Cotton Fighter',
                'slug' => 'cotton-fighter',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:42',
                'updated_at' => '2019-06-06 09:02:42',
                'deleted_at' => NULL,
            ),
            135 =>
            array (
                'id' => 136,
                'name' => 'Mineola',
                'name_l' => 'Mineola',
                'slug' => 'mineola',
                'description' => '0',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:42',
                'updated_at' => '2019-06-06 09:02:42',
                'deleted_at' => NULL,
            ),
            136 =>
            array (
                'id' => 137,
                'name' => 'Apairl',
                'name_l' => 'Apairl',
                'slug' => 'apairl',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:42',
                'updated_at' => '2019-06-06 09:02:42',
                'deleted_at' => NULL,
            ),
            137 =>
            array (
                'id' => 138,
                'name' => 'Muzca',
                'name_l' => 'Muzca',
                'slug' => 'muzca',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:42',
                'updated_at' => '2019-06-06 09:02:42',
                'deleted_at' => NULL,
            ),
            138 =>
            array (
                'id' => 139,
                'name' => 'Dolce The Label',
                'name_l' => 'Dolce The Label',
                'slug' => 'dolce-the-label',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:42',
                'updated_at' => '2019-06-06 09:02:42',
                'deleted_at' => NULL,
            ),
            139 =>
            array (
                'id' => 140,
                'name' => 'Starke',
                'name_l' => 'Starke',
                'slug' => 'starke',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:42',
                'updated_at' => '2019-06-06 09:02:42',
                'deleted_at' => NULL,
            ),
            140 =>
            array (
                'id' => 141,
                'name' => 'Story Of Rivhone',
                'name_l' => 'Story Of Rivhone',
                'slug' => 'story-of-rivhone',
                'description' => '0',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:43',
                'updated_at' => '2019-06-06 09:02:43',
                'deleted_at' => NULL,
            ),
            141 =>
            array (
                'id' => 142,
                'name' => 'Bananas Slipper',
                'name_l' => 'Bananas Slipper',
                'slug' => 'bananas-slipper',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:43',
                'updated_at' => '2019-06-06 09:02:43',
                'deleted_at' => NULL,
            ),
            142 =>
            array (
                'id' => 143,
                'name' => 'Horst',
                'name_l' => 'Horst',
                'slug' => 'horst',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:43',
                'updated_at' => '2019-06-06 09:02:43',
                'deleted_at' => NULL,
            ),
            143 =>
            array (
                'id' => 144,
                'name' => 'Dekade Time',
                'name_l' => 'Dekade Time',
                'slug' => 'dekade-time',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:43',
                'updated_at' => '2019-06-06 09:02:43',
                'deleted_at' => NULL,
            ),
            144 =>
            array (
                'id' => 145,
                'name' => 'Moscha',
                'name_l' => 'Moscha',
                'slug' => 'moscha',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:43',
                'updated_at' => '2019-06-06 09:02:43',
                'deleted_at' => NULL,
            ),
            145 =>
            array (
                'id' => 146,
                'name' => 'Chronox',
                'name_l' => 'Chronox',
                'slug' => 'chronox',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:43',
                'updated_at' => '2019-06-06 09:02:43',
                'deleted_at' => NULL,
            ),
            146 =>
            array (
                'id' => 147,
                'name' => 'Akanni',
                'name_l' => 'Akanni',
                'slug' => 'akanni',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:43',
                'updated_at' => '2019-06-06 09:02:43',
                'deleted_at' => NULL,
            ),
            147 =>
            array (
                'id' => 148,
                'name' => 'Anja The Label',
                'name_l' => 'Anja The Label',
                'slug' => 'anja-the-label',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:43',
                'updated_at' => '2019-06-06 09:02:43',
                'deleted_at' => NULL,
            ),
            148 =>
            array (
                'id' => 149,
                'name' => 'NAS',
                'name_l' => 'NAS',
                'slug' => 'nas',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:43',
                'updated_at' => '2019-06-06 09:02:43',
                'deleted_at' => NULL,
            ),
            149 =>
            array (
                'id' => 150,
                'name' => 'Anynome',
                'name_l' => 'Anynome',
                'slug' => 'anynome',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:43',
                'updated_at' => '2019-06-06 09:02:43',
                'deleted_at' => NULL,
            ),
            150 =>
            array (
                'id' => 151,
                'name' => 'Identt',
                'name_l' => 'Identt',
                'slug' => 'identt',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:44',
                'updated_at' => '2019-06-06 09:02:44',
                'deleted_at' => NULL,
            ),
            151 =>
            array (
                'id' => 152,
                'name' => 'Onii-San',
                'name_l' => 'Onii-San',
                'slug' => 'onii-san',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:44',
                'updated_at' => '2019-06-06 09:02:44',
                'deleted_at' => NULL,
            ),
            152 =>
            array (
                'id' => 153,
                'name' => 'Norm',
                'name_l' => 'Norm',
                'slug' => 'norm',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:44',
                'updated_at' => '2019-06-06 09:02:44',
                'deleted_at' => NULL,
            ),
            153 =>
            array (
                'id' => 154,
                'name' => 'Empathy',
                'name_l' => 'Empathy',
                'slug' => 'empathy',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:44',
                'updated_at' => '2019-06-06 09:02:44',
                'deleted_at' => NULL,
            ),
            154 =>
            array (
                'id' => 155,
                'name' => 'Noski Socks',
                'name_l' => 'Noski Socks',
                'slug' => 'noski-socks',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:44',
                'updated_at' => '2019-06-06 09:02:44',
                'deleted_at' => NULL,
            ),
            155 =>
            array (
                'id' => 156,
                'name' => 'WATT',
                'name_l' => 'WATT',
                'slug' => 'watt',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:44',
                'updated_at' => '2019-06-06 09:02:44',
                'deleted_at' => NULL,
            ),
            156 =>
            array (
                'id' => 157,
                'name' => 'Stradivarius',
                'name_l' => 'Stradivarius',
                'slug' => 'stradivarius',
                'description' => 'default',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:44',
                'updated_at' => '2019-06-06 09:02:44',
                'deleted_at' => NULL,
            ),
            157 =>
            array (
                'id' => 158,
                'name' => 'Fine Form',
                'name_l' => 'Fine Form',
                'slug' => 'fine-form',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:44',
                'updated_at' => '2019-06-06 09:02:44',
                'deleted_at' => NULL,
            ),
            158 =>
            array (
                'id' => 159,
                'name' => 'Pix Footwear',
                'name_l' => 'Pix Footwear',
                'slug' => 'pix-footwear',
                'description' => '0',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:44',
                'updated_at' => '2019-06-06 09:02:44',
                'deleted_at' => NULL,
            ),
            159 =>
            array (
                'id' => 160,
                'name' => 'Pix Footwear',
                'name_l' => 'Pix Footwear',
                'slug' => 'pix-footwear',
                'description' => '0',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:44',
                'updated_at' => '2019-06-06 09:02:44',
                'deleted_at' => NULL,
            ),
            160 =>
            array (
                'id' => 161,
                'name' => 'Wyne & Blair',
                'name_l' => 'Wyne & Blair',
                'slug' => 'wyne-blair',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:44',
                'updated_at' => '2019-06-06 09:02:44',
                'deleted_at' => NULL,
            ),
            161 =>
            array (
                'id' => 162,
                'name' => 'Toera Batik',
                'name_l' => 'Toera Batik',
                'slug' => 'toera-batik',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:45',
                'updated_at' => '2019-06-06 09:02:45',
                'deleted_at' => NULL,
            ),
            162 =>
            array (
                'id' => 163,
                'name' => 'Artfy Label',
                'name_l' => 'Artfy Label',
                'slug' => 'artfy-label',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:45',
                'updated_at' => '2019-06-06 09:02:45',
                'deleted_at' => NULL,
            ),
            163 =>
            array (
                'id' => 164,
                'name' => 'TAP Studio',
                'name_l' => 'TAP Studio',
                'slug' => 'tap-studio',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:45',
                'updated_at' => '2019-06-06 09:02:45',
                'deleted_at' => NULL,
            ),
            164 =>
            array (
                'id' => 165,
                'name' => 'Ulintando',
                'name_l' => 'Ulintando',
                'slug' => 'ulintando',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:45',
                'updated_at' => '2019-06-06 09:02:45',
                'deleted_at' => NULL,
            ),
            165 =>
            array (
                'id' => 166,
                'name' => 'Kakak Adik',
                'name_l' => 'Kakak Adik',
                'slug' => 'kakak-adik',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:45',
                'updated_at' => '2019-06-06 09:02:45',
                'deleted_at' => NULL,
            ),
            166 =>
            array (
                'id' => 167,
                'name' => 'Kehati Shoes',
                'name_l' => 'Kehati Shoes',
                'slug' => 'kehati-shoes',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:45',
                'updated_at' => '2019-06-06 09:02:45',
                'deleted_at' => NULL,
            ),
            167 =>
            array (
                'id' => 168,
                'name' => 'Herupa',
                'name_l' => 'Herupa',
                'slug' => 'herupa',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:45',
                'updated_at' => '2019-06-06 09:02:45',
                'deleted_at' => NULL,
            ),
            168 =>
            array (
                'id' => 169,
                'name' => 'Yeah Right Brand',
                'name_l' => 'Yeah Right Brand',
                'slug' => 'yeah-right-brand',
                'description' => '0',
                'status' => 0,
                'created_at' => '2019-06-06 09:02:45',
                'updated_at' => '2019-06-06 09:02:45',
                'deleted_at' => NULL,
            ),
            169 =>
            array (
                'id' => 170,
                'name' => 'Yeah Right Brand',
                'name_l' => 'Yeah Right Brand',
                'slug' => 'yeah-right-brand',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:45',
                'updated_at' => '2019-06-06 09:02:45',
                'deleted_at' => NULL,
            ),
            170 =>
            array (
                'id' => 171,
                'name' => 'Loro',
                'name_l' => 'Loro',
                'slug' => 'loro',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:45',
                'updated_at' => '2019-06-06 09:02:45',
                'deleted_at' => NULL,
            ),
            171 =>
            array (
                'id' => 172,
                'name' => 'Knitkini',
                'name_l' => 'Knitkini',
                'slug' => 'knitkini',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:46',
                'updated_at' => '2019-06-06 09:02:46',
                'deleted_at' => NULL,
            ),
            172 =>
            array (
                'id' => 173,
                'name' => 'Aimee',
                'name_l' => 'Aimee',
                'slug' => 'aimee',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:46',
                'updated_at' => '2019-06-06 09:02:46',
                'deleted_at' => NULL,
            ),
            173 =>
            array (
                'id' => 174,
                'name' => 'Adjani',
                'name_l' => 'Adjani',
                'slug' => 'adjani',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:46',
                'updated_at' => '2019-06-06 09:02:46',
                'deleted_at' => NULL,
            ),
            174 =>
            array (
                'id' => 175,
                'name' => 'Renoa',
                'name_l' => 'Renoa',
                'slug' => 'renoa',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:46',
                'updated_at' => '2019-06-06 09:02:46',
                'deleted_at' => NULL,
            ),
            175 =>
            array (
                'id' => 176,
                'name' => 'Autiv Fixin',
                'name_l' => 'Autiv Fixin',
                'slug' => 'autiv-fixin',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:46',
                'updated_at' => '2019-06-06 09:02:46',
                'deleted_at' => NULL,
            ),
            176 =>
            array (
                'id' => 177,
                'name' => 'Rumme',
                'name_l' => 'Rumme',
                'slug' => 'rumme',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:46',
                'updated_at' => '2019-06-06 09:02:46',
                'deleted_at' => NULL,
            ),
            177 =>
            array (
                'id' => 178,
                'name' => 'DJEJAC',
                'name_l' => 'DJEJAC',
                'slug' => 'djejac',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:46',
                'updated_at' => '2019-06-06 09:02:46',
                'deleted_at' => NULL,
            ),
            178 =>
            array (
                'id' => 179,
                'name' => 'YESZY.MFG',
                'name_l' => 'YESZY.MFG',
                'slug' => 'yeszymfg',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:46',
                'updated_at' => '2019-06-06 09:02:46',
                'deleted_at' => NULL,
            ),
            179 =>
            array (
                'id' => 180,
                'name' => 'RE',
                'name_l' => 'RE',
                'slug' => 're',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:46',
                'updated_at' => '2019-06-06 09:02:46',
                'deleted_at' => NULL,
            ),
            180 =>
            array (
                'id' => 181,
                'name' => 'Sleepynerd',
                'name_l' => 'Sleepynerd',
                'slug' => 'sleepynerd',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:47',
                'updated_at' => '2019-06-06 09:02:47',
                'deleted_at' => NULL,
            ),
            181 =>
            array (
                'id' => 182,
                'name' => 'Desired Experience',
                'name_l' => 'Desired Experience',
                'slug' => 'desired-experience',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:47',
                'updated_at' => '2019-06-06 09:02:47',
                'deleted_at' => NULL,
            ),
            182 =>
            array (
                'id' => 183,
                'name' => 'Jalin',
                'name_l' => 'Jalin',
                'slug' => 'jalin',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:47',
                'updated_at' => '2019-06-06 09:02:47',
                'deleted_at' => NULL,
            ),
            183 =>
            array (
                'id' => 184,
                'name' => 'she.her.hers.',
                'name_l' => 'she.her.hers.',
                'slug' => 'sheherhers',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:47',
                'updated_at' => '2019-06-06 09:02:47',
                'deleted_at' => NULL,
            ),
            184 =>
            array (
                'id' => 185,
                'name' => 'Bellwood Channel',
                'name_l' => 'Bellwood Channel',
                'slug' => 'bellwood-channel',
                'description' => '0',
                'status' => 1,
                'created_at' => '2019-06-06 09:02:47',
                'updated_at' => '2019-06-06 09:02:47',
                'deleted_at' => NULL,
            ),
        ));


    }
}
