<?php

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('categories')->delete();
        
        \DB::table('categories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Accessories',
                'name_l' => 'Accessories',
                'slug' => 'accessories',
                'parent_id' => NULL,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => 7,
                'old_id' => 43,
                'created_at' => '2019-06-06 09:08:56',
                'updated_at' => '2019-06-06 09:08:56',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Accessories',
                'name_l' => 'Accessories',
                'slug' => 'accessories-men',
                'parent_id' => 1,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => 6,
                'old_id' => 26,
                'created_at' => '2019-06-06 09:08:56',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Accessories',
                'name_l' => 'Accessories',
                'slug' => 'accessories-women',
                'parent_id' => 1,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => 6,
                'old_id' => 28,
                'created_at' => '2019-06-06 09:08:56',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Analog Watches',
                'name_l' => 'Analog Watches',
                'slug' => 'analog-watch-men',
                'parent_id' => 84,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 63,
                'created_at' => '2019-06-06 09:08:56',
                'updated_at' => '2019-06-06 09:09:01',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Analog Watches',
                'name_l' => 'Analog Watches',
                'slug' => 'analog-watch-women',
                'parent_id' => 1,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 64,
                'created_at' => '2019-06-06 09:08:56',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Ankle Socks',
                'name_l' => 'Ankle Socks',
                'slug' => 'ankle-socks',
                'parent_id' => 69,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 60,
                'created_at' => '2019-06-06 09:08:56',
                'updated_at' => '2019-06-06 09:09:01',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Ankle Socks',
                'name_l' => 'Ankle Socks',
                'slug' => 'ankle-socks-men',
                'parent_id' => 69,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 62,
                'created_at' => '2019-06-06 09:08:56',
                'updated_at' => '2019-06-06 09:09:01',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Backpacks',
                'name_l' => 'Backpacks',
                'slug' => 'backpacks',
                'parent_id' => 9,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 101,
                'created_at' => '2019-06-06 09:08:56',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Bags',
                'name_l' => 'Bags',
                'slug' => 'bags',
                'parent_id' => NULL,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => 3,
                'old_id' => 46,
                'created_at' => '2019-06-06 09:08:56',
                'updated_at' => '2019-06-06 09:08:56',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Beauty',
                'name_l' => 'Beauty',
                'slug' => 'beauty',
                'parent_id' => NULL,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => 6,
                'old_id' => 44,
                'created_at' => '2019-06-06 09:08:56',
                'updated_at' => '2019-06-06 09:08:56',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Bikinis',
                'name_l' => 'Bikinis',
                'slug' => 'bikini',
                'parent_id' => 72,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 73,
                'created_at' => '2019-06-06 09:08:56',
                'updated_at' => '2019-06-06 09:09:01',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Bottoms',
                'name_l' => 'Bottoms',
                'slug' => 'bottoms',
                'parent_id' => NULL,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => 1,
                'old_id' => 93,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:08:57',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Bottoms',
                'name_l' => 'Bottoms',
                'slug' => 'bottoms-men',
                'parent_id' => 999,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 34,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:08:57',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Bottoms',
                'name_l' => 'Bottoms',
                'slug' => 'bottoms-women',
                'parent_id' => 999,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 35,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:08:57',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Bras',
                'name_l' => 'Bras',
                'slug' => 'bras',
                'parent_id' => 19,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 82,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Caps',
                'name_l' => 'Caps',
                'slug' => 'caps-men',
                'parent_id' => 53,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 65,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Caps',
                'name_l' => 'Caps',
                'slug' => 'caps-women',
                'parent_id' => 53,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 66,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Casual Watch',
                'name_l' => 'Casual Watch',
                'slug' => 'casual-watch-men',
                'parent_id' => NULL,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 47,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:08:57',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Clothing',
                'name_l' => 'Clothing',
                'slug' => 'clothing',
                'parent_id' => NULL,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => 0,
                'old_id' => 42,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:08:57',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Clutch',
                'name_l' => 'Clutch',
                'slug' => 'clutch',
                'parent_id' => 9,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 104,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Clutch',
                'name_l' => 'Clutch',
                'slug' => 'clutch-men',
                'parent_id' => 9,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 59,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Clutch',
                'name_l' => 'Clutch',
                'slug' => 'clutch-women',
                'parent_id' => 9,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 81,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Crew Length Socks',
                'name_l' => 'Crew Length Socks',
                'slug' => 'crewlengthsocks-men',
                'parent_id' => 69,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 61,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:09:01',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Dress',
                'name_l' => 'Dress',
                'slug' => 'dress',
                'parent_id' => 19,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 31,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Eyelashes',
                'name_l' => 'Eyelashes',
                'slug' => 'eyelashes',
                'parent_id' => 10,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 83,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Flats',
                'name_l' => 'Flats',
                'slug' => 'flats',
                'parent_id' => 55,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 72,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Formal Shoes',
                'name_l' => 'Formal Shoes',
                'slug' => 'formal-shoes',
                'parent_id' => 55,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 55,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Glasses',
                'name_l' => 'Glasses',
                'slug' => 'glasses',
                'parent_id' => 1,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 109,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Hand Bags',
                'name_l' => 'Hand Bags',
                'slug' => 'handbag',
                'parent_id' => 9,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 110,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Hats',
                'name_l' => 'Hats',
                'slug' => 'hats',
                'parent_id' => 1,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 52,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Hats',
                'name_l' => 'Hats',
                'slug' => 'hats-men',
                'parent_id' => 1,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 94,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Hats',
                'name_l' => 'Hats',
                'slug' => 'hats-women',
                'parent_id' => 1,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 91,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Heels',
                'name_l' => 'Heels',
                'slug' => 'heels',
                'parent_id' => 55,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 92,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Intimates',
                'name_l' => 'Intimates',
                'slug' => 'intimates',
                'parent_id' => NULL,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 53,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:08:57',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Intimates',
                'name_l' => 'Intimates',
                'slug' => 'intimates-women',
                'parent_id' => 999,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 39,
                'created_at' => '2019-06-06 09:08:57',
                'updated_at' => '2019-06-06 09:08:57',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Jeans',
                'name_l' => 'Jeans',
                'slug' => 'jeans',
                'parent_id' => 12,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 84,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Jewelry',
                'name_l' => 'Jewelry',
                'slug' => 'jewelry',
                'parent_id' => 1,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 89,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Jumpsuits',
                'name_l' => 'Jumpsuits',
                'slug' => 'jumpsuits',
                'parent_id' => 19,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 86,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Lifestyle',
                'name_l' => 'Lifestyle',
                'slug' => 'lifestyle',
                'parent_id' => 1,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 102,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Lip',
                'name_l' => 'Lip',
                'slug' => 'lip',
                'parent_id' => 10,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 111,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Messenger Bag',
                'name_l' => 'Messenger Bag',
                'slug' => 'messengerbag',
                'parent_id' => 9,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 108,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'One Piece',
                'name_l' => 'One Piece',
                'slug' => 'onepiece',
                'parent_id' => 72,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 75,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:09:01',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Outerwear & Sweatshirts',
                'name_l' => 'Outerwear & Sweatshirts',
                'slug' => 'outerwear-men',
                'parent_id' => 19,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 36,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Outerwear & Sweatshirts',
                'name_l' => 'Outerwear & Sweatshirts',
                'slug' => 'outerwear-sweatshirts',
                'parent_id' => 19,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 107,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Outerwear',
                'name_l' => 'Outerwear',
                'slug' => 'outerwear-women',
                'parent_id' => 19,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 37,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Pants',
                'name_l' => 'Pants',
                'slug' => 'pants',
                'parent_id' => 12,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 88,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Polos',
                'name_l' => 'Polos',
                'slug' => 'polo',
                'parent_id' => 19,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => 1,
                'old_id' => 27,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'Pouches',
                'name_l' => 'Pouches',
                'slug' => 'pouches-men',
                'parent_id' => 9,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 79,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Purses & Pouches',
                'name_l' => 'Purses & Pouches',
                'slug' => 'purses-pouches',
                'parent_id' => 9,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 80,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Pyjamas',
                'name_l' => 'Pyjamas',
                'slug' => 'pyjamas',
                'parent_id' => 19,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 96,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Sandals',
                'name_l' => 'Sandals',
                'slug' => 'sandals',
                'parent_id' => 55,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 103,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Scarves',
                'name_l' => 'Scarves',
                'slug' => 'scarves',
                'parent_id' => 1,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 95,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'Shirts',
                'name_l' => 'Shirts',
                'slug' => 'shirts',
                'parent_id' => 19,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 30,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Shirts',
                'name_l' => 'Shirts',
                'slug' => 'shirts-women',
                'parent_id' => 19,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 38,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'Shoes',
                'name_l' => 'Shoes',
                'slug' => 'shoes',
                'parent_id' => NULL,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => 2,
                'old_id' => 45,
                'created_at' => '2019-06-06 09:08:58',
                'updated_at' => '2019-06-06 09:08:58',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'Shoes',
                'name_l' => 'Shoes',
                'slug' => 'shoes-men',
                'parent_id' => 999,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 32,
                'created_at' => '2019-06-06 09:08:59',
                'updated_at' => '2019-06-06 09:08:59',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'Shoes',
                'name_l' => 'Shoes',
                'slug' => 'shoes-women',
                'parent_id' => 999,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 40,
                'created_at' => '2019-06-06 09:08:59',
                'updated_at' => '2019-06-06 09:08:59',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'Shorts',
                'name_l' => 'Shorts',
                'slug' => 'shorts',
                'parent_id' => 12,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 69,
                'created_at' => '2019-06-06 09:08:59',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'Skirts',
                'name_l' => 'Skirts',
                'slug' => 'skirts',
                'parent_id' => 12,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 85,
                'created_at' => '2019-06-06 09:08:59',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'Sleepwear',
                'name_l' => 'Sleepwear',
                'slug' => 'sleepwear',
                'parent_id' => NULL,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => 4,
                'old_id' => 71,
                'created_at' => '2019-06-06 09:08:59',
                'updated_at' => '2019-06-06 09:08:59',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'Sleepwear',
                'name_l' => 'Sleepwear',
                'slug' => 'sleepwear-women',
                'parent_id' => 60,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 70,
                'created_at' => '2019-06-06 09:08:59',
                'updated_at' => '2019-06-06 09:09:01',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'Sling Bags',
                'name_l' => 'Sling Bags',
                'slug' => 'sling-bags',
                'parent_id' => 9,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 58,
                'created_at' => '2019-06-06 09:08:59',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'Sling Bags',
                'name_l' => 'Sling Bags',
                'slug' => 'sling-women',
                'parent_id' => 9,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 78,
                'created_at' => '2019-06-06 09:08:59',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'Slip on',
                'name_l' => 'Slip on',
                'slug' => 'slip-on-men',
                'parent_id' => 55,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 98,
                'created_at' => '2019-06-06 09:08:59',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'Slip on',
                'name_l' => 'Slip on',
                'slug' => 'slipon',
                'parent_id' => 55,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 100,
                'created_at' => '2019-06-06 09:08:59',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'Sneakers',
                'name_l' => 'Sneakers',
                'slug' => 'sneakers',
                'parent_id' => 55,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 99,
                'created_at' => '2019-06-06 09:08:59',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'Sneakers',
                'name_l' => 'Sneakers',
                'slug' => 'sneakers-men',
                'parent_id' => 55,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 56,
                'created_at' => '2019-06-06 09:08:59',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'Sneakers',
                'name_l' => 'Sneakers',
                'slug' => 'sneakers-women',
                'parent_id' => 55,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 97,
                'created_at' => '2019-06-06 09:08:59',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'Socks',
                'name_l' => 'Socks',
                'slug' => 'socks',
                'parent_id' => 1,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 51,
                'created_at' => '2019-06-06 09:08:59',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'Socks',
                'name_l' => 'Socks',
                'slug' => 'socks-women',
                'parent_id' => 1,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 76,
                'created_at' => '2019-06-06 09:08:59',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'Swimsuit',
                'name_l' => 'Swimsuit',
                'slug' => 'swimsuit',
                'parent_id' => 72,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 74,
                'created_at' => '2019-06-06 09:08:59',
                'updated_at' => '2019-06-06 09:09:01',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'Swimwear',
                'name_l' => 'Swimwear',
                'slug' => 'swimwear',
                'parent_id' => NULL,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => 5,
                'old_id' => 54,
                'created_at' => '2019-06-06 09:08:59',
                'updated_at' => '2019-06-06 09:08:59',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'Swimwear',
                'name_l' => 'Swimwear',
                'slug' => 'swimwear-women',
                'parent_id' => 72,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 41,
                'created_at' => '2019-06-06 09:09:00',
                'updated_at' => '2019-06-06 09:09:01',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'T-shirts',
                'name_l' => 'T-shirts',
                'slug' => 't-shirts',
                'parent_id' => 19,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 29,
                'created_at' => '2019-06-06 09:09:00',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'Ties',
                'name_l' => 'Ties',
                'slug' => 'ties',
                'parent_id' => 1,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 67,
                'created_at' => '2019-06-06 09:09:00',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'Tops',
                'name_l' => 'Tops',
                'slug' => 'tops',
                'parent_id' => 19,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 33,
                'created_at' => '2019-06-06 09:09:00',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'Tote Bags',
                'name_l' => 'Tote Bags',
                'slug' => 'tote-men',
                'parent_id' => 9,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 57,
                'created_at' => '2019-06-06 09:09:00',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'Tote Bags',
                'name_l' => 'Tote Bags',
                'slug' => 'tote-women',
                'parent_id' => 9,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 77,
                'created_at' => '2019-06-06 09:09:00',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'Tote Bags',
                'name_l' => 'Tote Bags',
                'slug' => 'totes',
                'parent_id' => 9,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 105,
                'created_at' => '2019-06-06 09:09:00',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'Trousers',
                'name_l' => 'Trousers',
                'slug' => 'trousers',
                'parent_id' => 12,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 68,
                'created_at' => '2019-06-06 09:09:00',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'T-shirts',
                'name_l' => 'T-shirts',
                'slug' => 'tshirts-women',
                'parent_id' => 999,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 23,
                'created_at' => '2019-06-06 09:09:00',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'Wallet',
                'name_l' => 'Wallet',
                'slug' => 'wallet',
                'parent_id' => 1,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 106,
                'created_at' => '2019-06-06 09:09:00',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'Wallets',
                'name_l' => 'Wallets',
                'slug' => 'wallet-men',
                'parent_id' => 1,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 90,
                'created_at' => '2019-06-06 09:09:00',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'Watches',
                'name_l' => 'Watches',
                'slug' => 'watch',
                'parent_id' => 1,
                'status' => 1,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 50,
                'created_at' => '2019-06-06 09:09:00',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'Watch',
                'name_l' => 'Watch',
                'slug' => 'watch-men',
                'parent_id' => NULL,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 48,
                'created_at' => '2019-06-06 09:09:00',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'Watch',
                'name_l' => 'Watch',
                'slug' => 'watch-women',
                'parent_id' => NULL,
                'status' => 0,
                'description' => NULL,
                'description_l' => NULL,
                'image_url' => NULL,
                'order' => NULL,
                'old_id' => 49,
                'created_at' => '2019-06-06 09:09:00',
                'updated_at' => '2019-06-06 09:09:00',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}